# SKILLS

Skill.create(skill: "AJAX", num_of_projects: "6")
Skill.create(skill: "Amazon Web Services", num_of_projects: "3")
Skill.create(skill: "Behavior Driven Development", num_of_projects: "3")
Skill.create(skill: "CSS3", num_of_projects: "30")
Skill.create(skill: "Carrierwave Gem", num_of_projects: "3")
Skill.create(skill: "Mini Magick Gem", num_of_projects: "3")
Skill.create(skill: "Fog Gem", num_of_projects: "3")
Skill.create(skill: "Devise Gem", num_of_projects: "4")
Skill.create(skill: "Gravatar Integration", num_of_projects: "2")
Skill.create(skill: "HTML5", num_of_projects: "30")
Skill.create(skill: "JavaScript", num_of_projects: "15")
Skill.create(skill: "MVC", num_of_projects: "10")
Skill.create(skill: "Multi-Tenancy", num_of_projects: "1")
Skill.create(skill: "RSpec", num_of_projects: "20")
Skill.create(skill: "Capybara", num_of_projects: "5")
Skill.create(skill: "Ruby", num_of_projects: "30")
Skill.create(skill: "PostgreSQL", num_of_projects: "10")
Skill.create(skill: "SQL", num_of_projects: "15")
Skill.create(skill: "SASS", num_of_projects: "10")
Skill.create(skill: "SQLite3", num_of_projects: "10")
Skill.create(skill: "SendGrid", num_of_projects: "4")
Skill.create(skill: "Stripe", num_of_projects: "3")
Skill.create(skill: "TDD", num_of_projects: "20")
Skill.create(skill: "Yahoo API", num_of_projects: "1")
Skill.create(skill: "Google APIs", num_of_projects: "2")
Skill.create(skill: "jQuery", num_of_projects: "10")
Skill.create(skill: "Ruby on Rails", num_of_projects: "15")
Skill.create(skill: "Sinatra", num_of_projects: "6")
# Skill.create(skill: "React", num_of_projects: "0")
Skill.create(skill: "Python", num_of_projects: "8")
Skill.create(skill: "C#", num_of_projects: "4")
Skill.create(skill: "Unity", num_of_projects: "4")
# Skill.create(skill: "Node.js", num_of_projects: "0")
Skill.create(skill: "Bootstrap", num_of_projects: "6")
Skill.create(skill: "Materialize", num_of_projects: "8")
# Skill.create(skill: "Semantic UI", num_of_projects: "0")
# Skill.create(skill: "Django", num_of_projects: "0")
Skill.create(skill: "Angular 2", num_of_projects: "3")